### ISSUE TITLE
Implement & Usage Questions

### ISSUE THREAD

**Issue by alexanderGugel** [sky-uk/nowtv-web-navigation#51]
First issue - yey!

So I looked through the codebase and have a couple of questions/ changes that I would like to propose (happy to make those if everyone is ok with them).

# Use assertions instead of manual console.errors?

It might be a better idea to use something like [`invariant`](https://github.com/facebook/fbjs/blob/master/src/__forks__/invariant.js) or `assert` to make assertions instead of manually calling `console.error` all over the place.

That way we would get a proper call stack during development and it would be easier to minify (assuming the complete error messages are supposed to be excluded in production).

e.g.

```js
    if (!this._options.selector) {
      console.error('You must provide a selector e.g. NowTVGlobalNavigation.GlobalNav({selector: ".nav"})');
      return;
    }

    this._nav = document.querySelector(this._options.selector);

    if (!this._nav) {
      console.error('Element with selector "' + this._options.selector + '"not found');
      return;
    }
```

Could be much shorter and we would actually get a proper call stack (assuming pause on caught exception is enabled).

---

# UMD?

Is there any reason why there are two different builds for common and var (`browserCDN` and `react`)? Can't we use UMD?

---

# Actual HTMLElement instead of selector?

It looks like currently only string selectors are being accepted to define the container elements. Can we make this polymorphic? E.g. Why can't we pass in an actual HTMLElement?

This would have two advantages:

1. No more redundant DOM traversions.

  While a micro optimisation at this point (we're also not batching the DOM ops), it's still a blocking operation.

2. Less error prone

  Otherwise it might make sense to print a warning if there are multiple matching elements.

---

# GlobalNavRenderer?

Why is this a class? If it's called "Global", I would assume it's a singleton. Also it essentially only exposes two different methods, one of which is the constructor. Might make more sense to make this a method.

Also passing state via the actual object instance is kind of cumbersome IMO:

```js
  this._config = merge(response.data, this._options);
  let context = this._getHandlebarsContext();
  const markup = html(context);
```

```js
  _getHandlebarsContext() {
    let context = merge({}, this._config, {
      topNav: {
```

Why can't we pass it as an argument? Also the instance is being thrown away anyways, so this should probably simply be a method (config could be first arg and bound where needed).

Also defining 

```js
axios.get('http://localhost:8080/config.json')
```

as a configurable env var would make things easier in the future.

Also axios seems to be pretty huge and hardly minifiable. Does having promises for this specific method really outweigh the massive increase in footprint? Can't we just use `XMLHttpRequest`?

---

# getViewportWidth?

I don't think this is actually being used, but I have seen this pattern in a couple of places throughout the codebase:

```js
  if (window.matchMedia("(min-width: 400px)").matches) {
    return 'tablet';
  } else if (window.matchMedia("(min-width: 1024px)").matches) {
    return 'desktop';
  } else {
    return 'mobile';
  }
```

Hardcoding strings is probably not optimal for minification. Thoughts on using something like [keymirror](https://www.npmjs.com/package/keymirror) (that's what react is using under the hood)?

---

# Using constructors for side effects?

Constructors are being used for their side effects in a lot of places throughout the codebase.

## Example

```js
  constructor(element) {
    this.element = element;

    let options = {
      element: this.element.querySelector('[type=search]'),
      onFocus: this.focusCallback.bind(this),
      onBlur: this.blurCallback.bind(this)
    };

    new SearchInput(options);
  }

  focusCallback() {
    document.body.className += ' is-search-focused';
```

Is this intentional or a temporary solution? I'm not too worried if they are only mutating the DOM, but it's hard to debug if they're making XHR requests under the hood.

(https://jslinterrors.com/do-not-use-new-for-side-effects)

---

I understand that this codebase is in an early stage.
Thoughts about those points (most are very minor)?

Happy to make those changes if everyone is ok with that. Just didn't want to make weird overnight changes.

**Comment by benlancaster** [comment]
Thanks Alex, all good points! We have an issue open to handle Error Logging properly (#52). We also like the UMD idea, keen to see if we could make that one work, by all means fork and hack an example together if you get a chance?

I think most of the other things you mentioned fall under micro optimisations (with the exception of constructors) – we're trying to avoid optimising too soon at this stage while there's lots changing, but as soon as we approach our first shippable version we'll be looking to optimise where appropriate (including ditching the unused code!).

**Comment by benlancaster** [comment]
Closing now that we have issues for each item
